name: Test Self-Hosted
on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          python3 -m venv .venv
          
          .venv/bin/python3 -m pip install -e .
          .venv/bin/python3 -m pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
          .venv/bin/python3 -m pip install -r requirements-dev.txt -r requirements-ci.txt
          .venv/bin/python3 -m pip install wheel
          .venv/bin/python3 setup.py bdist_wheel
          .venv/bin/python3 -m pip install dist/PennyLane*.whl

      - run: |
          .venv/bin/python3 -m pytest -m gpu tests/
          
